package generator

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"strings"

	"github.com/theawakener0/MkLang/config"
)

// formatGo gofmts generated Go source.
func formatGo(src []byte) ([]byte, error) {
	formatted, err := format.Source(src)
	if err != nil {
		return nil, err
	}
	return formatted, nil
}

// renderTokenGo renders token/token.go: the token types plus the config's
// keyword and symbol tables.
func renderTokenGo(spec *config.Spec) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by MkLang. DO NOT EDIT.\n\n")
	b.WriteString(tokenSkeleton)

	b.WriteString("// keywords maps the configured spelling of each keyword to its canonical type.\n")
	b.WriteString("var keywords = map[string]TokenType{\n")
	for _, k := range config.SortedKeys(spec.Keywords) {
		fmt.Fprintf(&b, "\t%q: %s,\n", k, spec.Keywords[k])
	}
	b.WriteString("}\n\n")

	b.WriteString("// symbols maps the configured spelling of each operator/delimiter to its\n// canonical type. Longer spellings are matched first by the lexer.\n")
	b.WriteString("var symbols = map[string]TokenType{\n")
	for _, k := range config.SortedKeys(spec.Symbols) {
		fmt.Fprintf(&b, "\t%q: %s,\n", k, spec.Symbols[k])
	}
	b.WriteString("}\n")

	return formatGo(b.Bytes())
}

// renderSpecGo renders token/spec.go: the fixed Spec types plus the
// defaultSpec() body produced from the config.
func renderSpecGo(spec *config.Spec) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by MkLang. DO NOT EDIT.\n\n")
	b.WriteString(specSkeleton)
	b.WriteString(renderSpecBody(spec))
	b.WriteString(specTail)
	return formatGo(b.Bytes())
}

func renderSpecBody(spec *config.Spec) string {
	var b bytes.Buffer

	fmt.Fprintf(&b, "\t\tName:    %q,\n", spec.Name)
	fmt.Fprintf(&b, "\t\tModule:  %q,\n", spec.Module)
	fmt.Fprintf(&b, "\t\tVersion: %q,\n", spec.Version)

	f := spec.Features
	fmt.Fprintf(&b, "\t\tFeatures: Features{\n")
	fmt.Fprintf(&b, "\t\t\tFloats:              %t,\n", f.Floats)
	fmt.Fprintf(&b, "\t\t\tStrings:             %t,\n", f.Strings)
	fmt.Fprintf(&b, "\t\t\tArrays:              %t,\n", f.Arrays)
	fmt.Fprintf(&b, "\t\t\tHashes:              %t,\n", f.Hashes)
	fmt.Fprintf(&b, "\t\t\tForLoops:            %t,\n", f.ForLoops)
	fmt.Fprintf(&b, "\t\t\tInfiniteLoops:       %t,\n", f.InfiniteLoops)
	fmt.Fprintf(&b, "\t\t\tTry:                 %t,\n", f.Try)
	fmt.Fprintf(&b, "\t\t\tPrefixPostfixIncDec: %t,\n", f.PrefixPostfixIncDec)
	fmt.Fprintf(&b, "\t\t\tCompoundAssignment:  %t,\n", f.CompoundAssignment)
	fmt.Fprintf(&b, "\t\t\tElseIf:              %t,\n", f.ElseIf)
	fmt.Fprintf(&b, "\t\t\tMatrices:            %t,\n", f.Matrices)
	fmt.Fprintf(&b, "\t\t\tAutoSemicolons:      %t,\n", f.AutoSemicolons)
	fmt.Fprintf(&b, "\t\t\tComments:            %t,\n", f.Comments)
	fmt.Fprintf(&b, "\t\t\tBlockComments:       %t,\n", f.BlockComments)
	fmt.Fprintf(&b, "\t\t},\n")

	c := spec.Comments
	fmt.Fprintf(&b, "\t\tComments:   Comments{Line: %q, BlockStart: %q, BlockEnd: %q},\n", c.Line, c.BlockStart, c.BlockEnd)

	id := spec.Identifier
	fmt.Fprintf(&b, "\t\tIdentifier: Identifier{StartLetters: %t, ExtraStart: %q, PartLettersDigits: %t, ExtraPart: %q},\n",
		id.StartLetters, id.ExtraStart, id.PartLettersDigits, id.ExtraPart)

	st := spec.String
	fmt.Fprintf(&b, "\t\tString:     StringConfig{Delimiter: %q, EscapeSequences: %t},\n", st.Delimiter, st.EscapeSequences)

	fmt.Fprintf(&b, "\t\tBuiltins: map[string]string{\n")
	for _, k := range config.SortedKeys(spec.Builtins) {
		fmt.Fprintf(&b, "\t\t\t%q: %q,\n", k, spec.Builtins[k])
	}
	fmt.Fprintf(&b, "\t\t},\n")

	fmt.Fprintf(&b, "\t\tStatementEnd: []TokenType{\n")
	for _, name := range spec.StatementEnd {
		fmt.Fprintf(&b, "\t\t\t%s,\n", name)
	}
	fmt.Fprintf(&b, "\t\t},\n")

	o := spec.Output
	fmt.Fprintf(&b, "\t\tOutput: Output{\n")
	fmt.Fprintf(&b, "\t\t\tTrue:       %q,\n", o.True)
	fmt.Fprintf(&b, "\t\t\tFalse:      %q,\n", o.False)
	fmt.Fprintf(&b, "\t\t\tNull:       %q,\n", o.Null)
	fmt.Fprintf(&b, "\t\t\tBreak:      %q,\n", o.Break)
	fmt.Fprintf(&b, "\t\t\tContinue:   %q,\n", o.Continue)
	fmt.Fprintf(&b, "\t\t\tFunction:   %q,\n", o.Function)
	fmt.Fprintf(&b, "\t\t\tArrayOpen:  %q,\n", o.ArrayOpen)
	fmt.Fprintf(&b, "\t\t\tArrayClose: %q,\n", o.ArrayClose)
	fmt.Fprintf(&b, "\t\t\tArraySep:   %q,\n", o.ArraySep)
	fmt.Fprintf(&b, "\t\t\tHashOpen:   %q,\n", o.HashOpen)
	fmt.Fprintf(&b, "\t\t\tHashClose:  %q,\n", o.HashClose)
	fmt.Fprintf(&b, "\t\t\tHashSep:    %q,\n", o.HashSep)
	fmt.Fprintf(&b, "\t\t\tHashKeyVal: %q,\n", o.HashKeyVal)
	fmt.Fprintf(&b, "\t\t},\n")

	return b.String()
}

// renderMainGo renders the generated project's main.go: a small REPL runner
// plus script-file execution.
func renderMainGo(spec *config.Spec) ([]byte, error) {
	banner := fmt.Sprintf("===== %s v%s =====", spec.Name, spec.Version)
	bin := strings.ToLower(spec.Name)

	src := fmt.Sprintf(`package main

import (
	"fmt"
	"os"
	"os/user"

	"%s/repl"
)

var version = %q

const banner = %q

func main() {
	if len(os.Args) > 1 && (os.Args[1] == "-version" || os.Args[1] == "--version") {
		fmt.Printf("%s %%s\n", version)
		return
	}

	if len(os.Args) > 1 {
		source, err := os.ReadFile(os.Args[1])
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		repl.Execute(string(source), os.Stdout)
		return
	}

	user, err := user.Current()
	if err != nil {
		panic(err)
	}

	fmt.Printf("\x1b[0;34m%%s\x1b[0m\n", banner)
	fmt.Printf("\nHello %%s! Type the command here.\n", user.Username)

	repl.Start(os.Stdin, os.Stdout)
}
`, spec.Module, spec.Version, banner, bin)

	return formatGo([]byte(src))
}

// renderGoMod renders the generated project's go.mod. Generated projects have
// no external dependencies.
func renderGoMod(spec *config.Spec) []byte {
	return []byte(fmt.Sprintf("module %s\n\ngo 1.22.2\n", spec.Module))
}

// renderReadme renders a short README for the generated project.
func renderReadme(spec *config.Spec) []byte {
	bin := strings.ToLower(spec.Name)
	return []byte(fmt.Sprintf(`# %s

%s %s is a small, interpreted, dynamically typed language generated with
MkLang.

## Build

    go build -o %s .

## Run the REPL

    ./%s

## Run a script

    ./%s script.<ext>

## Regenerate

This project was generated from %q. Edit that file and run:

    mklang generate -config %q -out . -force

`, spec.Name, spec.Name, spec.Version, bin, bin, bin, "lang.json", "lang.json"))
}

// renderLangJSON renders the config that produced the project, so it can be
// edited and re-run through mklang.
func renderLangJSON(spec *config.Spec) []byte {
	data, err := json.MarshalIndent(spec, "", "  ")
	if err != nil {
		return []byte("{}\n")
	}
	return append(data, '\n')
}
